SYSTEM_NAME="movies"
SYSTEM_FULLNAME="Movies"
SYSTEM_MANUFACTURER="&#xf013; System"
SYSTEM_RELEASE="System"
SYSTEM_HARDWARE="System"
SYSTEM_PATH="/storage/roms/movies"
SYSTEM_EXTENSION=".3g2 .3gp .asf .avi .divx .f4v .flv .m2ts .m3u .m4v .mkv .mov .mp4 .mpeg .mpg .mts .ogm .ogv .ts .vob .webm .wmv"
SYSTEM_PLATFORM="movies"
SYSTEM_THEME="movies"
SYSTEM_WIKI_PATH="movies"
